################
### MONITORS ###
################

monitor = eDP-1, preferred, auto, 1.25
monitor = DP-1, preferred, auto-right, 1
monitor = , preferred, auto, 1

###################
### MY PROGRAMS ###
###################

$terminal    = kitty
$fileManager = yazi 
$menu        = /home/kernel_x23_6/.local/bin/rofi-launcher -show drun -modi "drun,window,clipboard:/home/kernel_x23_6/.local/bin/rofi-clipboard"
$browser     = firefox
$notes       = obsidian
$editor      = code
$editor-alt  = subl
$colorPicker = hyprpicker

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Firefox
env = MOZ_ENABLE_WAYLAND,1

# Nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Qt
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_STYLE_OVERRIDE,kvantum

# Toolkit backends
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# XDG
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

##############
### SOURCE ###
##############

source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/windowrules.conf
